# Check the web performace using
# lighthouse ci
# allow to show the page result for seo, performace, compatibility
#
# ******** NOTE *********
# Lighthouse only check your web result and platform

name: Lighthouse

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release & Publish"]
    types:
      - completed
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lighthouse:
    name: Lighthouse Testing the web on Node ${{matrix.node}}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://devcrates.site
          uploadArtifacts: true
          temporaryPublicStorage: true
